name: road_conditions_check

on:
  push:
    branches:
      - main
  schedule:
    # run action every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  build:
    # spin up virtual machine with latest version of ubuntu
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    # set up python version 3.8 on the ubuntu operating system virtual machine
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # install any require dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas
        pip install python-decouple
        pip install beautifulsoup4
        pip install lxml
    # run python script to pull and transform arcgis data to csv to heroku postgres server
    - name: Check Road Conditions
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python road_conditions_check.py
    - name: Commit and push if it changed
      run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
